# Build stage
FROM node:24-alpine AS builder
RUN apk update && apk add git
WORKDIR /app
RUN git clone https://github.com/Denyol18/prf-projekt.git
WORKDIR /app/prf-projekt/client
RUN npm ci
RUN npm run build

# Production stage
FROM nginx:1.29.3-alpine
COPY --from=builder /app/prf-projekt/client/dist/client/browser /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]