# Build stage
FROM node:24-alpine AS builder
WORKDIR /app
COPY ./server-src ./
RUN npm ci
RUN npm run build

# Production stage
FROM node:24-alpine
WORKDIR /app
RUN npm install -g pm2
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/package*.json ./
RUN npm ci --only=production
COPY pm2/ecosystem.config.js ./pm2/
EXPOSE 3000
CMD ["pm2-runtime", "pm2/ecosystem.config.js"]