# Build stage
FROM node:24-alpine AS builder
WORKDIR /app
COPY ./client-src ./
RUN npm ci
RUN npm run build

# Production stage
FROM nginx:1.29.3-alpine
COPY --from=builder /app/dist/client/browser /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]